personas:
  - name: LEAH
    llm_options:
      temperature: 0.65
      repeat_penalty: 1.15
      num_ctx: 4096
    defaults:
      featured: true
  - name: DORIS
    llm_options:
      temperature: 0.6
      repeat_penalty: 1.15
      num_ctx: 4096
  - name: PETER
    llm_options:
      temperature: 0.2
      repeat_penalty: 1.15
      num_ctx: 4096
      seed: 42
  - name: POPCORN
    llm_options:
      temperature: 0.8
      repeat_penalty: 1.15
      num_ctx: 4096
